import CalendarViewTexts from './CalendarViewTexts.json';

export default () => ({
    title: CalendarViewTexts.TITLE,
    description: CalendarViewTexts.DESCRIPTION,
    calendarTitle: 'Calendar',
    weeks: [
        [
            { id: 1, label: 1, isHoliday: false },
            { id: 2, label: 3, isHoliday: false },
            { id: 3, label: 3, isHoliday: false },
            { id: 4, label: 4, isHoliday: false },
            { id: 5, label: 5, isHoliday: false },
            { id: 6, label: 6, isHoliday: true },
            { id: 7, label: 7, isHoliday: true },
        ],
        [
            { id: 8, label: 1, isHoliday: false },
            { id: 9, label: 1, isHoliday: false },
            { id: 10, label: 1, isHoliday: false },
            { id: 11, label: 1, isHoliday: false },
            { id: 12, label: 1, isHoliday: false },
            { id: 13, label: 1, isHoliday: true },
            { id: 14, label: 1, isHoliday: true },
        ],
        [
            { id: 15, label: 1, isHoliday: false },
            { id: 16, label: 1, isHoliday: false },
            { id: 17, label: 1, isHoliday: false },
            { id: 18, label: 1, isHoliday: false },
            { id: 19, label: 1, isHoliday: false },
            { id: 20, label: 1, isHoliday: true },
            { id: 21, label: 1, isHoliday: true },
        ],
        [
            { id: 22, label: 1, isHoliday: false },
            { id: 23, label: 1, isHoliday: false },
            { id: 24, label: 1, isHoliday: false },
            { id: 25, label: 1, isHoliday: false },
            { id: 26, label: 1, isHoliday: false },
            { id: 27, label: 1, isHoliday: true },
            { id: 28, label: 1, isHoliday: true },
        ],
    ],
    dayOfWeeks: [
        { id: 'MON', label: 'Mon' },
        { id: 'TUE', label: 'Tue' },
        { id: 'WEN', label: 'Wen' },
        { id: 'THU', label: 'Thu' },
        { id: 'FRI', label: 'Fri' },
        { id: 'SAT', label: 'Sat' },
        { id: 'SUN', label: 'Sun' },
    ],
    menuItems: [{ text: 'Calendar', id: 'CALENDAR' }, { text: 'News', id: 'NEWS' }],
    todos: [],
    news: [],
});
